### ISSUE TITLE
你们是不是谢错人了？

### ISSUE THREAD

**Issue by vvvv3** [MSWorkers/support.996.ICU#110]
readme都说了 微软内部存这种996问题  这个项目是微软的员工支持的，而不是微软这个企业支持的
汗。。。

**Comment by Naville** [comment]
头脑发热脑子不太好使的silent majority是这样的啦

**Comment by chennqqi** [comment]
Microsoft and GitHub Workers Support 996.ICU

**Comment by xtydev** [comment]
估计很多人都只看了标题…个人行为和公司行为要分分清啊

**Comment by LipYoung** [comment]
# 微软和 GitHub 员工宣布支持 996.ICU 运动

这句中文本来就有歧义的。

**Comment by xtydev** [comment]
不仅谢错人 而且还错把问题区当成了留言板…
让这里flooded with duplicates不太妥当吧…
想要表示支持/感谢的话点个👍或是在同一个issue下面留名就行了

**Comment by realKaboom** [comment]
Github 贴吧化

**Comment by Tedko** [comment]
duplicate with #149
