### ISSUE TITLE
我谨代表个人, 宣布以后完全支持IE9以上浏览器

### ISSUE THREAD

**Issue by 8pig** [MSWorkers/support.996.ICU#123]

**Comment by AntiMoron** [comment]
You can completely make your website support edge instead of IE.

**Comment by ShaneYS** [comment]
no no no , support microsoft is ok, support IE is not ok.

**Comment by soapmiko** [comment]
Edge了解一下

**Comment by 8pig** [comment]
> Edge了解一下

edge 内核了解一下

**Comment by BensonLaur** [comment]
see #184 #110

**Comment by daysonhw** [comment]
chromium了解一下

**Comment by gsw945** [comment]
everyone can register a hotmail email account, not only web browser.

**Comment by Tedko** [comment]
Thx
