### ISSUE TITLE
无产阶级联合起来粉碎资产阶级的枷锁

### ISSUE THREAD

**Issue by namelcx** [MSWorkers/support.996.ICU#133]

**Comment by gaoypChina** [comment]
从来就没有什么救世主，
也不靠神仙皇帝！
要创造人类的幸福，
全靠我们自己！
我们要夺回劳动果实，
让思想冲破牢笼！
快把那炉火烧得通红，
趁热打铁才能成功！

**Comment by etata** [comment]
无产阶级应该站起来。。。

**Comment by Tedko** [comment]
duplicate with #113
