### ISSUE TITLE
快到五一国际劳动节了

### ISSUE THREAD

**Issue by lcgtpr** [MSWorkers/support.996.ICU#140]
程序员也是劳动者，我们不希望百多年前大资本大工厂剥削压迫工人的手段在当今的IT业复活

**Comment by tzc123** [comment]
> 程序员也是劳动者，我们不希望百多年前大资本大工厂剥削压迫工人的手段在当今的IT业复活

已经复活了，必须掐灭。

**Comment by Tedko** [comment]
see #184 
可以在别的issue讨论
