### ISSUE TITLE
这个 Repo 是个人行为还是公司行为？

### ISSUE THREAD

**Issue by imfht** [MSWorkers/support.996.ICU#149]
Hello：
    想问一下这个 repo 是个人账号还是公司账号？
    在Twitter 频道没有关于这个 Repo 的任何资料，也没有任何资料来证明账号的身份。

**Comment by Tedko** [comment]
> In response to these events, we, the workers of Microsoft and GitHub, support the 996.ICU movement and stand in solidarity with tech workers in China. We know this is a problem that crosses national borders. These same issues permeate across full time and contingent jobs at Microsoft and the industry as a whole. Another reason we must take a stand in solidarity with Chinese workers is that history tells us that multinational companies will pit workers against each other in a race to the bottom as they outsource jobs and take advantage of weak labor standards in the pursuit of profit. We have to come together across national boundaries to ensure just working conditions for everyone around the globe.

**Comment by Tedko** [comment]
He don't speak Chinese.

**Comment by imfht** [comment]
Hello, I wanner ask you.
who created this repository?
The workers of Microsoft and GitHub? or Just someone here the news and create this repo?

谁创立的这个 repo，是支援996.ICU的微软员工还是热心网友看了新闻之后创建的这个 repo?

forgive my poor english ;-D.

**Comment by Symoncn** [comment]
> He don't speak Chinese.

does't

**Comment by MSWorkers** [comment]
This repo was created by Microsoft Workers/Employees. It is not a Microsoft account.

**Comment by imfht** [comment]
@MSWorkers  How could prove 
It would be better if you can say something in your official Twitter.

Anyway, thanks a lot!

**Comment by xtydev** [comment]
> 谁创立的这个 repo，是支援996.ICU的微软员工还是热心网友看了新闻之后创建的这个 repo?

员工的个人行为

**Comment by waynebaby** [comment]
> This repo was created by Microsoft Workers/Employees. It is not a Microsoft account.
> 这个repo是微软员工创作的，不是公司账号



> @MSWorkers  How could prove
> It would be better if you can say something in your official Twitter.
> Anyway, thanks a lot!

it does not matter. who signed it are using account linked with msft employee account.,

For example, me

**Comment by xiaohuilam** [comment]
Whatever this repository owner is...
I do never wanna pay for ICU or pay the issurance for others' ICU

**Comment by yodjj** [comment]
**聊天室 —— 没有自我审查**

**https://gitter.im/chinapolitics/Gate**

**TOR 浏览器 8.0.8 —— 绕过GFW**

![TOR 浏览器](https://raw.githubusercontent.com/mjstest/orgb1/fa270a800386564b0071bd8eb367b17d/2019-04-06_22-27-39.png?raw=true)

**https://chinagate.gitlab.io**

**Comment by Tedko** [comment]
@yodjj  广告不太好

**Comment by Tedko** [comment]
我看中文翻译的歧义已经pr改了。这个我先close了。

**Comment by GewitterHyperboreanCaldera** [comment]
个人支持吧。。。。。。
