### ISSUE TITLE
It’s time to sing a 《The Internationale》/是时候唱一首国际歌了

### ISSUE THREAD

**Issue by wckgo** [MSWorkers/support.996.ICU#180]
Arise ye workers from your slumbers
Arise ye prisoners of want
For reason in revolt now thunders
And at last ends the age of cant.
Away with all your superstitions
Servile masses arise, arise
We'll change henceforth the old tradition
And spurn the dust to win the prize.
So comrades, come rally
And the last fight let us face
The Internationale unites the human race.
So comrades, come rally
And the last fight let us face
The Internationale unites the human race.
No more deluded by reaction
On tyrants only we'll make war
The soldiers too will take strike action
They'll break ranks and fight no more
And if those cannibals keep trying
To sacrifice us to their pride
They soon shall hear the bullets flying
We'll shoot the generals on our own side.
No saviour from on high delivers
No faith have we in prince or peer
Our own right hand the chains must shiver
Chains of hatred, greed and fear
E'er the thieves will out with their booty
And give to all a happier lot.
Each [those] at the forge must do their duty
And we'll strike while the iron is hot.
---------------------------------------------------
起来，饥寒交迫的奴隶！

起来，全世界受苦的人！

满腔的热血已经沸腾，

要为真理而斗争！

旧世界打个落花流水，

奴隶们起来，起来！

不要说我们一无所有，

我们要做天下的主人！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

从来就没有什么救世主，

也不靠神仙皇帝！

要创造人类的幸福，

全靠我们自己！

我们要夺回劳动果实，

让思想冲破牢笼！

快把那炉火烧得通红，

趁热打铁才能成功！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

压迫的国家，空洞的法律，

苛捐杂税榨穷苦。

富豪们没有任何义务，

穷人的权利只是空话。

被沉沦的“平等”呻吟已久，

“平等”需要新的法律：

“没有无义务的权利，

也没有无权利的义务！”

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

矿井和铁路的帝王，

在神坛上奇丑无比。

除了掠夺别人的劳动，

他们还做过些什么？

在这帮人的保险柜里，

放的是劳动者的果实。

从剥削者的手里，

人民只是讨回血债。

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

国王用谎言来欺骗我们，

我们要联合向暴君开战！

让战士们在军队里罢工，

停止镇压离开暴力机器！

如果他们坚持护卫敌人，

让我们英勇牺牲，

他们将会知道我们的子弹，

会射向我们自己的将军。

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

是谁创造了人类世界？

是我们劳动群众！

一切归劳动者所有，

哪能容得寄生虫？

最可恨那些毒蛇猛兽，

吃尽了我们的血肉！

一旦把它们消灭干净，

鲜红的太阳照遍全球！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

这是最后的斗争，团结起来到明天，

英特纳雄耐尔就一定要实现！

**Comment by Tedko** [comment]
#182
