### ISSUE TITLE
当今圣上纳德拉今天修福报了吗

### ISSUE THREAD

**Issue by neruthes** [MSWorkers/support.996.ICU#185]
![IMG_7930](https://user-images.githubusercontent.com/2139261/56571749-20781900-65ad-11e9-8d69-9c4b5aa19106.PNG)

**Comment by BensonLaur** [comment]
#184

**Comment by jp1017** [comment]
阿弥陀佛

**Comment by SuperZiLu** [comment]
纳德拉是啥啊

**Comment by troy351** [comment]
@SuperZiLu 微软CEO
