### ISSUE TITLE
Add whitespace between Chinese characters and English characters.

### ISSUE THREAD

**Issue by fakeinc** [MSWorkers/support.996.ICU#19]
See https://github.com/sparanoid/chinese-copywriting-guidelines.
Adding more spaces is a good practice when writing Chinese with mixed English words, so please do it. Thanks!

**Comment by Tedko** [comment]
Thx. will do

**Comment by fakeinc** [comment]
@Tedko Thanks!

**Comment by Tedko** [comment]
https://github.com/MSWorkers/support.996.ICU/pull/24
