### ISSUE TITLE
Don't be a bystander

### ISSUE THREAD

**Issue by githubmll** [MSWorkers/support.996.ICU#196]
![github](https://user-images.githubusercontent.com/17825339/56575037-57731c80-65f7-11e9-98d0-44dc95fee353.png)

关键时刻，大家都做旁观者，这张图很能说明问题。。

**Comment by Chenhw2017** [comment]
是这个理





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by Tedko** [comment]
Duplicate with #90 
Thank you!
