### ISSUE TITLE
卸载360.腾讯浏览器

### ISSUE THREAD

**Issue by dantingx** [MSWorkers/support.996.ICU#298]

**Comment by ZhuPeng** [comment]
大家应该用 Chrome 的多一点


> From WeChat Mini Programe: [GitHub Trending Hub](https://github.com/ZhuPeng/mp-githubtrending)

**Comment by zenwan** [comment]
程序员有用360浏览器的？？？

**Comment by Tedko** [comment]
duplicate with #323 
see #184 
可以在别的issue一起讨论。 Thx

**Comment by dantingx** [comment]
> 程序员有用360浏览器的？？？

大部分还是用chrome的。。但是很多C#、C++开发，还是用360之类的伪国产浏览器。。。
