### ISSUE TITLE
Order of add new names

### ISSUE THREAD

**Issue by simon300000** [MSWorkers/support.996.ICU#307]
Since there is no order requirement,
I suggest everyone making pull request adding name to a random place between other names, which can reduce:
1. Risk of responsibility
2. avoid Conflict

Consider put this idea into Contribution.md?

**Comment by Tedko** [comment]
sure. @MSWorkers  whats ur opinion

**Comment by formulahendry** [comment]
Maybe sort name in alphabetical order?

**Comment by MSWorkers** [comment]
+1 great idea!

**Comment by MSWorkers** [comment]
resolved: #cbc39a3
