### ISSUE TITLE
就业岗位不能被 996 缩减，反对 996 就是促进增加就业岗位。

### ISSUE THREAD

**Issue by nufeng74** [MSWorkers/support.996.ICU#34]
就业岗位不能被 996 缩减，反对 996 就是促进增加就业岗位。

**Comment by NextBoy** [comment]
![image](https://user-images.githubusercontent.com/32335760/56554548-a3589e00-65c4-11e9-9f84-a5c61ed49575.png)

**Comment by LeonXtp** [comment]
越来越多的人开始认识到奋斗、公平竞争、就业机会、踮脚效应、囚徒困境等之间与资本之间的关系了

**Comment by Tedko** [comment]
duplicate with #111
