### ISSUE TITLE
Microsoft enterprise service departments perform 996 work schedule in China

### ISSUE THREAD

**Issue by iamybj** [MSWorkers/support.996.ICU#347]
本来外包就是给别人干活，那就应该像大爷一样被当大爷供着。但是在中国微软搞外包的部门却大搞996，而且推广微软实验性的所谓“新”技术，毒害中国年轻开发者。

就算外包员工不是微软正式员工，但是外包的管理人员应该是微软员工。外企外国人不怎么加班，自己是中国人，在外企工作却让中国人996加班。这样的汉奸难道就和微软没有关系？

本人虽然没做过外包，但是这些部门打着微软的旗号，外围再搞一堆狗一样的MVP，整天打着微软的旗号忽悠坑害中国单纯的年轻开发者学习微软的小白鼠技术，这是不是祸国殃民？

有些微软的管理人员，自己吃香的喝辣的不加班，却让中国开发者被微软技术套牢，让中国开发者经常996加班，这是什么情况？

谁都知道微软的技术都是商业技术，比尔盖子为了赚钱从他当IBM懂事的妈那里拿来的项目。赚钱并没有错，但是这些人却为了赚钱故意诱骗中国年轻开发者，而且还胡说什么微软都是最新技术最先进技术，而且自己享受让这些年轻中国人996加班供养他们，这是什么意思？

另外曝光携程下属公司途家网不但996，而且暴力裁员，拒不支付加班费。曝光网址 https://www.tujia.xyz

**Comment by Tedko** [comment]
@MSWorkers 

As MSWorkers stated in the README:

>In response to these events, we, the workers of Microsoft and GitHub, support the 996.ICU movement and stand in solidarity with tech workers in China. We know this is a problem that crosses national borders. These same issues permeate across full time and contingent jobs at Microsoft and the industry as a whole. Another reason we must take a stand in solidarity with Chinese workers is that history tells us that multinational companies will pit workers against each other in a race to the bottom as they outsource jobs and take advantage of weak labor standards in the pursuit of profit. We have to come together across national boundaries to ensure just working conditions for everyone around the globe.

**Comment by MSWorkers** [comment]
@iamybj, Thanks for the message. This is exactly why we must stand in solidarity with the 996 movement in China and support workers there. Do you know which vendor in China Microsoft uses for outsourcing that engages in 996 work practices?

**Comment by iamybj** [comment]
> @iamybj, Thanks for the message. This is exactly why we must stand in solidarity with the 996 movement in China and support workers there. Do you know which vendor in China Microsoft uses for outsourcing that engages in 996 work practices?

I heard that the Microsoft enterprise service department has 996 work schedule in China.
This is an outsource department. The administrators of this department are Microsoft's employees, but workers are not.
Maybe Microsoft's formal employee do not work 996, but Chinese administrators of Microsoft enslave other Chinese works in this department. Ugly Chinese.
Microsoft developing technology almost completely fails in China now, no young people study Microsoft technology again. That's because of those ugly Microsoft management employees.
All those management employees in this department and MVPs in China should be fired completely.

**Comment by yeungs1996** [comment]
what you pointed can be a serious issue that not only the Microsoft developers but also the Microsoft CELA should get involved. 
with that being said, you may be care about your languages since it was too intense in this scenario. It dose rise the concern but it also makes you look dramatic. I would suggest you to provide more details including actual work-spaces, the contents of the development. Also , please do not include company's current/former senior leadership's name in this case. It is inappropriate to do so on GitHub , you may go ahead to do it on BLIND.

**Comment by xixixixixixix** [comment]
> @iamybj, Thanks for the message. This is exactly why we must stand in solidarity with the 996 movement in China and support workers there. Do you know which vendor in China Microsoft uses for outsourcing that engages in 996 work practices?

@MSWorkers , are you seriously? please read what the guy said:
"本来外包就是给别人干活，那就应该像大爷一样被当大爷供着"

Bing translator:
Originally outsourcing is to work for others, it should be like a master as a master of the supply

Google translator:
"I was originally outsourced to work for others, and it should be like a grandfather."

This guy is insane.

**Comment by yzhong94** [comment]
@xixixixixixix  have to chime in here.  You are reading this incorrectly - perhaps due to the translator.  What he is saying is that while he understands that outsourcing sucks (meaning that you have to do the work regardless of how absurd the work is), he does not expect Microsoft's vendor companies to have a 996 schedule while Microsoft itself prioritizes work life balance.

**Comment by iamybj** [comment]
Wow you are all political correctness?
Being polite equals hypocritical.

**Comment by iamybj** [comment]
> > @iamybj, Thanks for the message. This is exactly why we must stand in solidarity with the 996 movement in China and support workers there. Do you know which vendor in China Microsoft uses for outsourcing that engages in 996 work practices?
> 
> @MSWorkers , are you seriously? please read what the guy said:
> "本来外包就是给别人干活，那就应该像大爷一样被当大爷供着"
> 
> Bing translator:
> Originally outsourcing is to work for others, it should be like a master as a master of the supply
> 
> Google translator:
> "I was originally outsourced to work for others, and it should be like a grandfather."
> 
> This guy is insane.

你个煞笔是中国人吧，在老外面前装有礼貌、献媚的？你这么这么贱？装礼貌就显得你高大上了？装知道茴香6钟写法就显得你牛逼了？中国人怎么这么多你这种垃圾虚伪、虚荣的败类。

**Comment by iamybj** [comment]
@xixixixixixix 
你个煞笔是中国人吧，在老外面前装有礼貌、献媚的？你这么这么贱？装礼貌就显得你高大上了？装知道茴香6钟写法就显得你牛逼了？中国人怎么这么多你这种垃圾虚伪、虚荣的败类。

**Comment by Tedko** [comment]
> @xixixixixixix @yeungs1996
> 你两个煞笔是中国人吧，给微软做外包的垃圾？在老外面前装有礼貌、献媚的？你怎么这么贱？装礼貌就显得你高大上了？装知道茴香6钟写法就显得你牛逼了？中国人怎么这么多你这种垃圾虚伪、虚荣的败类。


Please do not post anything that includes contents of name calling, defamation, harassment, threats, sedition, obscenity, or pornography. For example, do not use vulgar or insulting language; do not spread hateful or intolerant speech based on someone else's ethnicity, race, nationality, sex, gender identity, religion, sexual orientation, age, or physical disabilities; similarly, do not promote any organisations that disseminate such speech.

**Comment by purp1e** [comment]
在这发这个没什么意义吧,  这个repo仅仅代表个人, 跟公司没关系.
如果你对微软有意见(虽然我对它并不感冒) , 可以去别的地方发牢骚.你来错地方了.

**Comment by iamybj** [comment]
> 在这发这个没什么意义吧, 这个repo仅仅代表个人, 跟公司没关系.
> 如果你对微软有意见(虽然我对它并不感冒) , 可以去别的地方发牢骚.你来错地方了.

你个贱逼又出来一个装正经的，你算个什么狗东西？你再装逼你也只是一个码畜！

**Comment by purp1e** [comment]
可怜之人必有可恨之处啊, 还失业半年,  谁雇用你真是倒霉啊. 
@Tedko 关闭这个 issues 吧,  这就是疯狗罢了.

**Comment by iamybj** [comment]
> 可怜之人必有可恨之处啊, 还失业半年, 谁雇用你真是倒霉啊.
> @Tedko 关闭这个 issues 吧, 这就是疯狗罢了.



> 可怜之人必有可恨之处啊, 还失业半年, 谁雇用你真是倒霉啊.
> @Tedko 关闭这个 issues 吧, 这就是疯狗罢了.

不如你这个贱逼啊，自己是个傻屌，还想装高大上的掩盖自己的逼样。

**Comment by Tedko** [comment]
> > 可怜之人必有可恨之处啊, 还失业半年, 谁雇用你真是倒霉啊.
> > @Tedko 关闭这个 issues 吧, 这就是疯狗罢了.
> 
> > 可怜之人必有可恨之处啊, 还失业半年, 谁雇用你真是倒霉啊.
> > @Tedko 关闭这个 issues 吧, 这就是疯狗罢了.
> 
> 不如你这个贱逼啊，自己是个傻屌，还想装高大上的掩盖自己的逼样。

Please do not post anything that includes contents of name calling, defamation, harassment, threats, sedition, obscenity, or pornography. For example, do not use vulgar or insulting language; do not spread hateful or intolerant speech based on someone else's ethnicity, race, nationality, sex, gender identity, religion, sexual orientation, age, or physical disabilities; similarly, do not promote any organisations that disseminate such speech.
