### ISSUE TITLE
Anti-996 License

### ISSUE THREAD

**Issue by zenwan** [MSWorkers/support.996.ICU#358]
[Anti-996 License](https://github.com/996icu/996.ICU/blob/master/LICENSE)

The purpose of this license is to prevent anti-labour-law companies from using the software or codes under the license, and force those companies to weigh their way of working

See a[ full list of projects](https://github.com/996icu/996.ICU/blob/master/awesomelist/README.md) under Anti-996 License

This draft is adapted from the MIT license. For more detailed explanation, please see Wiki. This license is designed to be compatible with all major open source licenses.

For law professionals or anyone who is willing to contribute to future version directly, please go to[ Anti-996-License-1.0](https://github.com/kattgu7/Anti-996-License). Thank you.

**Comment by Tedko** [comment]
yeah Katt and I drafted the current version.

**Comment by Tedko** [comment]
已经pr
