### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by huangjianke** [MSWorkers/support.996.ICU#37]
👍

**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by NextBoy** [comment]
![image](https://user-images.githubusercontent.com/32335760/56554526-963baf00-65c4-11e9-9860-78f4b7bba313.png)
