### ISSUE TITLE
是否有可能组织一次反996罢工？

### ISSUE THREAD

**Issue by alxddhuang** [MSWorkers/support.996.ICU#375]
[《**中华人民共和国宪法**》](http://www.npc.gov.cn/npc/xinwen/2018-03/22/content_2052489.htm)第二章第三十五条：“中华人民共和国公民有言论、出版、集会、结社、游行、示威的自由。”现在是否到了可以组织一次罢工的时候了？舆论声浪再大，得到的实际成果仍然近乎为零，唯有行动才能打开局面吧。怎么组织？

**Comment by Tedko** [comment]
#184
