### ISSUE TITLE
我想让这图火，行么？

### ISSUE THREAD

**Issue by NextBoy** [MSWorkers/support.996.ICU#42]
![image](https://user-images.githubusercontent.com/32335760/56554493-7d32fe00-65c4-11e9-9d28-122f760688de.png)

**Comment by aboutmydreams** [comment]
自愿的劳动当然光荣。

**Comment by nufeng74** [comment]
996 就是变相的缩减就业岗位，让更多的人参与劳动参与就业，这是社会和企业的责任和义务。玩命的劳动并非光荣，而是自取灭亡，合理的劳动健康的劳动才光荣。
