### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by arnold0kang** [MSWorkers/support.996.ICU#496]
delete

**Comment by arnold0kang** [comment]
这就相当于，富人家的孩子天天大鱼大肉，看见穷人家的孩子粗茶淡饭后，就怂恿穷人家的孩子起来造反一样，却不管穷人家到底负担得起不。毕竟别人家乱了，在里面朱门酒肉的时候可以添加点乐子话题

**Comment by alxddhuang** [comment]
我希望管理员可以屏蔽这类人，这里不是发展骂战的地方，如果你支持996.ICU，请给出建议，如果不支持，请离开。

**Comment by vvvv3** [comment]
脑子有坑？@Tedko

**Comment by Yuan-Zhuo** [comment]
我只能说“哀其不幸，怒其不争”。
首先人家的劳动成果凭什么给你这种败类施舍，更何况微软在对中国的产品版权上已经仁至义尽，个人和小作坊基本不管；
其次给你加薪让你996，只不过是给国内资本家多一点剩余价值，而不是你狭隘的民族主义、被愚弄的国家情怀所理解的奋斗；
最后，人家是在github上支持，而不是你所谓的在你家门口怂恿，更何况从事996的可不一定是你这种穷人，国内年薪百万者而被迫996也大有人在！

**Comment by zwipyf** [comment]
强化自己

**Comment by arnold0kang** [comment]
本人要说明的是，第一 本人同样反对强迫的996，如果为了自我实现，或者有偿的情况下除外。第二 国内IT行业算是非常自由话竞争的市场，良禽择木而栖，有那么多公司可以按时上下班，为何不做自由的选择，如果连公司都不能自由的选择，自己没能力，又何必怪别人。第三，商业利益上面，没有什么狗屁仁至义尽。所谓的价值观在价值面前不堪一击，不然google 微软也不回和美国政府合作，这个是都知道的事情。第四，本人反对以任何狗屁价值观来怂恿，干预这个民族的事情。第六，钱不是天上掉下来的，如果倒退100年，如果我们船坚炮利，我们也可以通过强盗行为获取利益。第七，如果能提高效率，我相信，996会消失，但提高效率的前提是不断的提升，提升需要的不断的训练。
