### ISSUE TITLE
真想要高层重视起来，我们只需要「郭文贵爆料革命 · 启蒙开智入门指南」

### ISSUE THREAD

**Issue by Pangu2020together** [MSWorkers/support.996.ICU#577]
https://github.com/ourhimalayas/txt/issues/1

**Comment by alxddhuang** [comment]
此人是一个煽动家，反共，建议屏蔽吧。

**Comment by huanghe2015** [comment]
又来了，这国怎定体问。

**Comment by Pangu2020together** [comment]
@alxddhuang 斯德哥尔摩综合征又犯了？你也配姓赵？

**Comment by alxddhuang** [comment]
@MSWorkers 建议删除这个 issue 并屏蔽这个人吧。

**Comment by soulofc** [comment]
你也配姓赵？






在 2019-05-08 10:32:02，"Alexander D Huang" <notifications@github.com> 写道：


此人是一个煽动家，反共，建议屏蔽吧。

**Comment by chenzw98** [comment]
那人就是个跳梁小丑

**Comment by Tedko** [comment]
#184
