### ISSUE TITLE
支持996.ICU项目为假？微软圈粉是真？

### ISSUE THREAD

**Issue by yuanxin7835** [MSWorkers/support.996.ICU#604]
**文中假借支持中国开发者发起的996.IUC项目之名，矛头直指腾讯、阿里巴巴等浏览器，通篇都是商业竞争的味
诶 不知微软会不会把github玩坏啊**

**Comment by iamybj** [comment]
微软的垃圾你还信啊。
微软自己就是骗中国码农的垃圾。
