### ISSUE TITLE
建立一个 996公司查询

### ISSUE THREAD

**Issue by haoqing-yan** [MSWorkers/support.996.ICU#662]
通过查询公司法院被劳动制裁信息，以及失信信息；然后相对应的建立名单，再附上相对应的新闻信息。

**Comment by anti715** [comment]
这个996icu已经做了。
请访问discord
https://discord.gg/EdvvQGA
和996icu首页的slack

在群内通过指令查询
![Snipaste_](https://user-images.githubusercontent.com/71186260/99211206-c9770c00-2802-11eb-90f2-2ece0b1a01be.png)
