### ISSUE TITLE
我们永远也不可能指望资本的同情，现在的法定工作制度是先辈们用鲜血与勇气铸造的，在维护本阶级的利益的时候，这个阶级的每个人都不应当置身事外

### ISSUE THREAD

**Issue by zibuyu69** [MSWorkers/support.996.ICU#90]

**Comment by a1094426901** [comment]
ε=(´ο｀*)))唉

**Comment by ztygalaxy** [comment]
是啊，许多人以为这是我们IT界自己的事情，但殊不知，我们是在维护自己的权利，也是在维护那本法律的尊严，站在那部法律后面的，是千千万万的中国劳动者，是千千万万的万家灯火，是千千万万的合家团圆。

**Comment by Mogeko** [comment]
#184

**Comment by Tedko** [comment]
Thank you for the post. I am going to close this one based on #184
